-- ---------------------------------------------------------------------------
-- DADOS DE DEMONSTRACAO para a tela de Relatorios (30 dias, 72 entregas).
--
-- Serve so para voce ver os graficos populados antes de ter volume real.
--
-- Rodar:
--   npx wrangler d1 execute hub-logistico --local --file=./seed-demo.sql
--
-- Apagar depois:
--   npx wrangler d1 execute hub-logistico --local --command "DELETE FROM deliveries WHERE id_pedido LIKE 'DEMO-%';"
--
-- NAO rode em producao: sujaria o relatorio de verdade.
-- ---------------------------------------------------------------------------

INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-1', 'motoboy', 13.53, 47, 'concluida', '2026-07-06T18:16:00.000Z', 'demo-1', 'Diego Alves', 'Sion', 75.63, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-2', '99', 19.48, 39, 'concluida', '2026-07-06T17:27:00.000Z', 'demo-2', 'Fabio Melo', 'Sion', 57.78, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-3', 'motoboy', 18.2, 41, 'concluida', '2026-07-07T21:09:00.000Z', 'demo-3', 'Diego Alves', 'Lourdes', 73.01, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-4', 'motoboy', 18.73, 41, 'concluida', '2026-07-08T19:43:00.000Z', 'demo-4', 'Hugo Torres', 'Savassi', 50.87, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-5', 'uber', 16.26, 40, 'concluida', '2026-07-08T17:46:00.000Z', 'demo-5', 'Fabio Melo', 'Savassi', 49.1, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-6', 'uber', 22.35, 45, 'concluida', '2026-07-09T16:11:00.000Z', 'demo-6', 'Gisele Pinto', 'Centro', 100.21, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-7', '99', 17.66, 33, 'concluida', '2026-07-09T18:23:00.000Z', 'demo-7', 'Hugo Torres', 'Funcionarios', 87.34, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-8', 'ifood', 20.34, 28, 'concluida', '2026-07-10T20:49:00.000Z', 'demo-8', 'Elisa Rocha', 'Savassi', 121.93, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-9', 'uber', 22.58, 30, 'concluida', '2026-07-10T17:02:00.000Z', 'demo-9', 'Hugo Torres', 'Funcionarios', 91.93, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-10', 'motoboy', 14.72, 29, 'concluida', '2026-07-10T21:05:00.000Z', 'demo-10', 'Elisa Rocha', 'Savassi', 73.87, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-11', 'uber', 22.33, 37, 'concluida', '2026-07-11T20:13:00.000Z', 'demo-11', 'Hugo Torres', 'Centro', 113.66, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-12', '99', 17.16, 34, 'concluida', '2026-07-12T18:29:00.000Z', 'demo-12', 'Elisa Rocha', 'Lourdes', 123.39, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-13', 'motoboy', 13.93, 38, 'concluida', '2026-07-13T18:04:00.000Z', 'demo-13', 'Diego Alves', 'Funcionarios', 110.53, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-14', 'uber', 23.49, 41, 'concluida', '2026-07-13T20:35:00.000Z', 'demo-14', 'Elisa Rocha', 'Santo Antonio', 123.33, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-15', 'motoboy', 15.39, 40, 'concluida', '2026-07-13T20:49:00.000Z', 'demo-15', 'Bruno Lima', 'Santo Antonio', 82.48, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-16', 'motoboy', 16.87, 34, 'concluida', '2026-07-14T20:32:00.000Z', 'demo-16', 'Carla Dias', 'Santo Antonio', 132.96, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-17', 'uber', 21.08, 38, 'concluida', '2026-07-14T21:42:00.000Z', 'demo-17', 'Diego Alves', 'Lourdes', 77.65, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-18', 'uber', 17.61, 28, 'concluida', '2026-07-14T15:49:00.000Z', 'demo-18', 'Diego Alves', 'Sion', 134.81, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-19', 'uber', 16.9, 34, 'concluida', '2026-07-15T15:57:00.000Z', 'demo-19', 'Bruno Lima', 'Funcionarios', 115.6, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-20', 'motoboy', 19.62, 35, 'concluida', '2026-07-15T16:38:00.000Z', 'demo-20', 'Gisele Pinto', 'Lourdes', 66.68, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-21', 'ifood', 15.24, 30, 'concluida', '2026-07-16T19:19:00.000Z', 'demo-21', 'Hugo Torres', 'Funcionarios', 100.08, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-22', 'uber', 17.5, 29, 'concluida', '2026-07-16T15:19:00.000Z', 'demo-22', 'Diego Alves', 'Lourdes', 70.96, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-23', 'uber', 19.79, 38, 'concluida', '2026-07-16T15:31:00.000Z', 'demo-23', 'Elisa Rocha', 'Lourdes', 82.85, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-24', 'motoboy', 16.39, 40, 'concluida', '2026-07-17T16:48:00.000Z', 'demo-24', 'Fabio Melo', 'Funcionarios', 82.15, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-25', 'uber', 22.76, 47, 'concluida', '2026-07-18T18:46:00.000Z', 'demo-25', 'Diego Alves', 'Centro', 124.58, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-26', 'motoboy', 19.67, 50, 'concluida', '2026-07-18T20:27:00.000Z', 'demo-26', 'Ana Souza', 'Santo Antonio', 127.1, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-27', 'ifood', 21.08, 41, 'concluida', '2026-07-19T18:07:00.000Z', 'demo-27', 'Gisele Pinto', 'Savassi', 105.14, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-28', 'uber', 19.25, 34, 'concluida', '2026-07-19T17:30:00.000Z', 'demo-28', 'Gisele Pinto', 'Funcionarios', 72.96, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-29', '99', 18.95, 43, 'concluida', '2026-07-19T20:35:00.000Z', 'demo-29', 'Bruno Lima', 'Lourdes', 89.6, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-30', 'motoboy', 14.61, 30, 'concluida', '2026-07-19T19:05:00.000Z', 'demo-30', 'Carla Dias', 'Centro', 100.09, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-31', 'motoboy', 19.15, 47, 'concluida', '2026-07-20T18:13:00.000Z', 'demo-31', 'Fabio Melo', 'Centro', 78.19, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-32', 'uber', 21.98, 41, 'concluida', '2026-07-21T17:03:00.000Z', 'demo-32', 'Elisa Rocha', 'Savassi', 60.92, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-33', 'motoboy', 14.76, 33, 'concluida', '2026-07-21T15:50:00.000Z', 'demo-33', 'Ana Souza', 'Savassi', 47.19, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-34', 'uber', 21.11, 36, 'concluida', '2026-07-22T19:17:00.000Z', 'demo-34', 'Diego Alves', 'Funcionarios', 73.05, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-35', 'uber', 19.22, 43, 'concluida', '2026-07-22T16:47:00.000Z', 'demo-35', 'Hugo Torres', 'Lourdes', 128.42, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-36', 'motoboy', 16.07, 49, 'concluida', '2026-07-22T17:08:00.000Z', 'demo-36', 'Diego Alves', 'Santo Antonio', 88.32, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-37', 'motoboy', 14.39, 43, 'concluida', '2026-07-23T21:34:00.000Z', 'demo-37', 'Hugo Torres', 'Santo Antonio', 116.9, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-38', 'uber', 16.63, 50, 'concluida', '2026-07-23T16:03:00.000Z', 'demo-38', 'Hugo Torres', 'Santo Antonio', 78.14, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-39', 'uber', 18.67, 38, 'concluida', '2026-07-23T16:54:00.000Z', 'demo-39', 'Ana Souza', 'Sion', 134.74, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-40', 'uber', 20.19, 47, 'concluida', '2026-07-24T21:22:00.000Z', 'demo-40', 'Fabio Melo', 'Lourdes', 72.94, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-41', 'uber', 14.55, 41, 'concluida', '2026-07-24T18:52:00.000Z', 'demo-41', 'Hugo Torres', 'Sion', 79.62, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-42', 'motoboy', 12.79, 34, 'concluida', '2026-07-24T16:14:00.000Z', 'demo-42', 'Diego Alves', 'Centro', 62.3, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-43', 'motoboy', 19.57, 43, 'concluida', '2026-07-24T15:32:00.000Z', 'demo-43', 'Carla Dias', 'Funcionarios', 115.33, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-44', 'uber', 20.03, 32, 'concluida', '2026-07-25T18:23:00.000Z', 'demo-44', 'Carla Dias', 'Savassi', 123.59, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-45', 'motoboy', 17.05, 37, 'concluida', '2026-07-26T20:03:00.000Z', 'demo-45', 'Elisa Rocha', 'Santo Antonio', 106.79, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-46', '99', 18.68, 35, 'concluida', '2026-07-26T16:00:00.000Z', 'demo-46', 'Ana Souza', 'Savassi', 73.06, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-47', '99', 20.43, 37, 'concluida', '2026-07-26T16:31:00.000Z', 'demo-47', 'Hugo Torres', 'Centro', 83.44, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-48', 'uber', 14.98, 34, 'concluida', '2026-07-26T20:50:00.000Z', 'demo-48', 'Gisele Pinto', 'Funcionarios', 63.73, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-49', 'uber', 15.93, 42, 'concluida', '2026-07-27T17:56:00.000Z', 'demo-49', 'Ana Souza', 'Sion', 123.33, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-50', 'uber', 21.78, 30, 'concluida', '2026-07-27T21:14:00.000Z', 'demo-50', 'Diego Alves', 'Savassi', 71.24, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-51', 'motoboy', 19.36, 41, 'concluida', '2026-07-28T19:15:00.000Z', 'demo-51', 'Hugo Torres', 'Lourdes', 133.09, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-52', 'motoboy', 16.34, 37, 'concluida', '2026-07-28T21:05:00.000Z', 'demo-52', 'Ana Souza', 'Savassi', 112.01, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-53', 'motoboy', 15.19, 47, 'concluida', '2026-07-29T19:01:00.000Z', 'demo-53', 'Ana Souza', 'Funcionarios', 63.5, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-54', 'motoboy', 12.78, 32, 'concluida', '2026-07-29T16:53:00.000Z', 'demo-54', 'Gisele Pinto', 'Santo Antonio', 52.79, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-55', 'uber', 16.83, 37, 'concluida', '2026-07-29T15:51:00.000Z', 'demo-55', 'Diego Alves', 'Funcionarios', 112.42, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-56', 'motoboy', 17.89, 36, 'concluida', '2026-07-30T21:45:00.000Z', 'demo-56', 'Fabio Melo', 'Lourdes', 108.39, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-57', 'uber', 21.9, 50, 'concluida', '2026-07-30T18:29:00.000Z', 'demo-57', 'Elisa Rocha', 'Savassi', 70.4, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-58', 'uber', 23.19, 36, 'concluida', '2026-07-30T17:47:00.000Z', 'demo-58', 'Bruno Lima', 'Sion', 67.15, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-59', 'motoboy', 13.97, 46, 'concluida', '2026-07-31T16:16:00.000Z', 'demo-59', 'Hugo Torres', 'Funcionarios', 120.23, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-60', '99', 13.97, 30, 'concluida', '2026-07-31T17:15:00.000Z', 'demo-60', 'Bruno Lima', 'Centro', 115.4, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-61', 'uber', 18.29, 44, 'concluida', '2026-07-31T19:29:00.000Z', 'demo-61', 'Gisele Pinto', 'Santo Antonio', 94.66, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-62', 'motoboy', 14.39, 40, 'concluida', '2026-08-01T19:53:00.000Z', 'demo-62', 'Ana Souza', 'Savassi', 64.03, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-63', 'uber', 16.6, 29, 'concluida', '2026-08-01T17:52:00.000Z', 'demo-63', 'Diego Alves', 'Funcionarios', 86.69, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-64', '99', 14.98, 34, 'concluida', '2026-08-01T17:04:00.000Z', 'demo-64', 'Hugo Torres', 'Santo Antonio', 118.08, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-65', 'motoboy', 17.74, 38, 'concluida', '2026-08-02T21:35:00.000Z', 'demo-65', 'Carla Dias', 'Lourdes', 63.47, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-66', 'uber', 20.55, 36, 'concluida', '2026-08-02T19:52:00.000Z', 'demo-66', 'Carla Dias', 'Lourdes', 61.2, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-67', 'motoboy', 13.16, 33, 'concluida', '2026-08-02T17:56:00.000Z', 'demo-67', 'Hugo Torres', 'Lourdes', 100.13, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-68', 'uber', 18.67, 36, 'concluida', '2026-08-03T19:08:00.000Z', 'demo-68', 'Diego Alves', 'Lourdes', 81.8, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-69', 'uber', 19.04, 44, 'concluida', '2026-08-03T16:34:00.000Z', 'demo-69', 'Fabio Melo', 'Santo Antonio', 87.15, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-70', 'motoboy', 19.53, 40, 'concluida', '2026-08-03T15:00:00.000Z', 'demo-70', 'Diego Alves', 'Funcionarios', 87.88, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-71', 'motoboy', 12.2, 41, 'concluida', '2026-08-04T19:19:00.000Z', 'demo-71', 'Ana Souza', 'Lourdes', 69.03, 'demo@restaurante.com');
INSERT OR IGNORE INTO deliveries (id_pedido, plataforma_escolhida, valor_pago, eta_minutos, status, data_criacao, delivery_id_externo, cliente_nome, bairro, valor_pedido, despachado_por) VALUES ('DEMO-72', 'ifood', 14.2, 48, 'concluida', '2026-08-04T17:13:00.000Z', 'demo-72', 'Bruno Lima', 'Centro', 117.16, 'demo@restaurante.com');
